# Generated by Django 5.2.11 on 2026-02-28 04:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subtask', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='needed_hours',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
