# Generated by Django 5.2.11 on 2026-03-15 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subtask', '0003_alter_subtask_needed_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En Progreso'), ('completed', 'Completado'), ('postponed', 'Pospuesta')], default='pending', max_length=50),
        ),
    ]
