# Generated by Django 5.2.11 on 2026-03-19 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subtask', '0004_subtask_note_alter_subtask_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subtask',
            options={'ordering': ['planification_date', 'created_at']},
        ),
    ]
