# Generated by Django 5.2.11 on 2026-02-17 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_task_priority_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='descrip',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
