# Generated by Django 5.2.11 on 2026-02-17 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_task_descrip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='descrip',
        ),
        migrations.AddField(
            model_name='task',
            name='progress',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='task',
            name='subject',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='task',
            name='total_hours',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='task',
            name='type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
